server:
  port: 3002

spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/active_fitness_db
      database: active_fitness_db

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

kafka:
  topic:
    name: active-topic
