spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/aaifitnessdb
      database: aifitnessdb
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.ai_service.model.Activity #this tells that convert incoming json into this class object
        spring.json.trusted.packages: "*"

server:
  port: 3003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
kafka:
  topic:
    name: active-topic
gemini:
  url: ${gemini_url}
  key: ${gemini_key}