server:
  port: 3003

spring:
  data:
    mongodb:
      uri: mongodb://mongo-db:27017/ai_fitness_db
      database: ai_fitness_db

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.ai_service.model.Activity
        spring.json.trusted.packages: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

kafka:
  topic:
    name: active-topic

gemini:
  url: ${gemini_url}
  key: ${gemini_key}
