spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_db
    username: root
    password: Abhay@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 3001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/