server:
  port: 3001

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/fitness_db
    username: root
    password: Abhay@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
